import { describe, expect, it } from "vitest";
import { desktopKey, parseChord, playwrightChord, splitSequence, type DesktopKey } from "../src/keys.js";

describe("keys", () => {
  it.each([["Return", [[], "Return"]], ["ctrl+s", [["ctrl"], "s"]], ["ctrl+shift+Escape", [["ctrl", "shift"], "Escape"]], ["Control_L+alt+Tab", [["ctrl", "alt"], "Tab"]], ["super", [["cmd"], null]], ["ctrl+alt", [["ctrl", "alt"], null]], ["cmd+Win+a", [["cmd"], "a"]], ["ctrl++", [["ctrl"], "+"]], ["+", [[], "+"]]] as const)("parses %s", (chord, expected) => expect(parseChord(chord)).toEqual(expected));
  it.each(["a+ctrl", "ctrl+", "ctrl++shift", "Return+a"])("refuses malformed chord %s", (chord) => expect(() => parseChord(chord)).toThrow());
  it("splits sequences and handles space", () => { expect(splitSequence("ctrl+a BackSpace")).toEqual(["ctrl+a", "BackSpace"]); expect(splitSequence(" ")).toEqual(["space"]); expect(() => splitSequence("")).toThrow(); });
  it.each([["Return", { daytona: "enter", keysym: "Return", shift: false, char: null }], ["enter", { daytona: "enter", keysym: "Return", shift: false, char: null }], ["Page_Up", { daytona: "pageup", keysym: "Prior", shift: false, char: null }], ["pagedown", { daytona: "pagedown", keysym: "Next", shift: false, char: null }], ["BackSpace", { daytona: "backspace", keysym: "BackSpace", shift: false, char: null }], ["F5", { daytona: "f5", keysym: "F5", shift: false, char: null }], ["a", { daytona: "a", keysym: "a", shift: false, char: "a" }], ["7", { daytona: "7", keysym: "7", shift: false, char: "7" }], ["A", { daytona: "a", keysym: "a", shift: true, char: "A" }], ["!", { daytona: "1", keysym: "1", shift: true, char: "!" }], ["exclam", { daytona: "1", keysym: "1", shift: true, char: "!" }], ["?", { daytona: "/", keysym: "slash", shift: true, char: "?" }], ["minus", { daytona: "-", keysym: "minus", shift: false, char: "-" }], ["/", { daytona: "/", keysym: "slash", shift: false, char: "/" }], [" ", { daytona: "space", keysym: "space", shift: false, char: " " }], ["KP_1", { daytona: "num1", keysym: "KP_1", shift: false, char: null }], ["KP_Decimal", { daytona: "num_decimal", keysym: "KP_Decimal", shift: false, char: null }], ["KP_Enter", { daytona: null, keysym: "KP_Enter", shift: false, char: null }], ["KP_Add", { daytona: null, keysym: "KP_Add", shift: false, char: null }], ["KP_Subtract", { daytona: null, keysym: "KP_Subtract", shift: false, char: null }], ["KP_Multiply", { daytona: null, keysym: "KP_Multiply", shift: false, char: null }], ["KP_Divide", { daytona: null, keysym: "KP_Divide", shift: false, char: null }], ["é", { daytona: null, keysym: "U00E9", shift: false, char: "é" }], ["XF86AudioMute", { daytona: null, keysym: "XF86AudioMute", shift: false, char: null }]] as const satisfies ReadonlyArray<readonly [string, DesktopKey]>)("maps %s", (token, expected) => expect(desktopKey(token)).toEqual(expected));
  it.each([["Return", "Enter"], ["ctrl+shift+t", "Control+Shift+t"], ["cmd+a", "Meta+a"], ["Page_Up", "PageUp"], ["BackSpace", "Backspace"], ["Escape", "Escape"], ["alt+Left", "Alt+ArrowLeft"], ["A", "A"], ["exclam", "!"], ["space", "Space"], ["shift", "Shift"], ["PrintScreen", "PrintScreen"]])("converts %s for Playwright", (chord, expected) => expect(playwrightChord(chord)).toBe(expected));
  it.each([["+", ["+"]], ["plus", ["+"]], ["ctrl++", ["Control", "+"]], ["shift++", ["Shift", "+"]], ["ctrl+shift+t", ["Control", "Shift", "t"]], ["ctrl+plus", ["Control", "+"]]] as const)("preserves plus in %s", (chord, pressed) => { const keys: string[] = []; let building = ""; for (const char of playwrightChord(chord)) { if (char === "+" && building) { keys.push(building); building = ""; } else building += char; } keys.push(building); expect(keys).toEqual(pressed); });
});
