"""Daytona sandbox code executor for smolagents.

Implements the public smolagents remote-executor contract on top of Daytona's
code interpreter: an isolated sandbox with a stateful interpreter context that
preserves variables and imports across execution steps.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from daytona import Daytona
from smolagents import AgentError, CodeOutput, LogLevel, RemotePythonExecutor

if TYPE_CHECKING:
    from smolagents import AgentLogger


class DaytonaExecutor(RemotePythonExecutor):
    """Remote Python code executor running in a Daytona sandbox.

    Each executor owns one sandbox and one interpreter context, created at
    construction time and released by :meth:`cleanup`. Python state (variables,
    imports, tool definitions) persists across steps within the context.

    Registered under the ``smolagents.executors`` entry-point group as
    ``daytona``, so ``CodeAgent(executor_type="daytona")`` resolves to this
    class once the package is installed.

    Args:
        additional_imports: Additional Python packages to install in the sandbox.
        logger: Logger to use for output and errors.
        allow_pickle: Whether to allow pickle fallback when serializing objects
            that cannot be safely serialized to JSON. Keep the default ``False``
            unless you fully trust the execution environment.
        **kwargs: Forwarded to ``Daytona().create()``, e.g. ``params``
            (``CreateSandboxFromSnapshotParams`` or ``CreateSandboxFromImageParams``)
            and ``timeout``.
    """

    # Daytona's interpreter reports only `Exception` subclasses in its structured
    # error output, so the final-answer control-flow exception generated by the
    # base class must not derive from `BaseException`.
    FINAL_ANSWER_EXCEPTION_BASE = "Exception"

    def __init__(
        self,
        additional_imports: list[str],
        logger: "AgentLogger",
        allow_pickle: bool = False,
        **kwargs: Any,
    ):
        super().__init__(additional_imports, logger, allow_pickle)
        self._daytona = Daytona()
        self.sandbox = self._daytona.create(**kwargs)
        try:
            self.context = self.sandbox.code_interpreter.create_context()
            self.installed_packages = self.install_packages(additional_imports)
        except BaseException:
            # The sandbox is a remote resource created by this constructor: if the
            # rest of the initialization fails, the caller never receives the
            # instance and could not release it, so release it here.
            self.cleanup()
            raise
        self.logger.log("Daytona sandbox is running", level=LogLevel.INFO)

    def run_code_raise_errors(self, code: str) -> CodeOutput:
        """Execute Python code in the sandbox and return the result.

        Args:
            code: Python code to execute.

        Returns:
            Code output containing the result, logs, and whether it is the final answer.

        Raises:
            AgentError: If the executed code raised an error in the sandbox.
        """
        result = self.sandbox.code_interpreter.run_code(code, context=self.context)

        logs = result.stdout
        if result.stderr:
            logs = f"{logs}\n{result.stderr}".strip()

        if result.error:
            if result.error.name == self.FINAL_ANSWER_EXCEPTION:
                final_answer = self.deserialize_final_answer(result.error.value, self.allow_pickle)
                return CodeOutput(output=final_answer, logs=logs, is_final_answer=True)

            error_message = (
                f"{logs}\n"
                f"Executing code yielded an error:\n"
                f"{result.error.name}\n"
                f"{result.error.value}\n"
                f"{result.error.traceback}"
            )
            raise AgentError(error_message, self.logger)

        return CodeOutput(output=result.stdout.strip() or None, logs=logs, is_final_answer=False)

    def cleanup(self) -> None:
        """Release the Daytona sandbox.

        Idempotent and safe to call at any point, including after a partially
        failed initialization, per the smolagents executor contract.
        """
        try:
            if hasattr(self, "sandbox"):
                self.logger.log("Shutting down Daytona sandbox...", level=LogLevel.INFO)
                self.sandbox.delete()
                del self.sandbox
                self.logger.log("Daytona sandbox cleanup completed", level=LogLevel.INFO)
        except Exception as e:
            self.logger.log_error(f"Error during Daytona cleanup: {e}")
