"""Daytona sandbox code executor for smolagents.

Implements the public smolagents remote-executor contract on top of Daytona's
code interpreter: an isolated sandbox with a stateful interpreter context that
preserves variables and imports across execution steps.
"""

from __future__ import annotations

from textwrap import dedent
from typing import TYPE_CHECKING, Any

from daytona import Daytona
from smolagents import AgentError, CodeOutput, LogLevel, RemotePythonExecutor

if TYPE_CHECKING:
    from smolagents import AgentLogger


class DaytonaExecutor(RemotePythonExecutor):
    """Remote Python code executor running in a Daytona sandbox.

    Each executor owns one sandbox and one interpreter context, created at
    construction time and released by :meth:`cleanup`. Python state (variables,
    imports, tool definitions) persists across steps within the context.

    Registered under the ``smolagents.executors`` entry-point group as
    ``daytona``, so ``CodeAgent(executor_type="daytona")`` resolves to this
    class once the package is installed.

    Args:
        additional_imports: Additional Python packages to install in the sandbox.
        logger: Logger to use for output and errors.
        allow_pickle: Whether to allow pickle fallback when serializing objects
            that cannot be safely serialized to JSON. Keep the default ``False``
            unless you fully trust the execution environment.
        **kwargs: Forwarded to ``Daytona().create()``, e.g. ``params``
            (``CreateSandboxFromSnapshotParams`` or ``CreateSandboxFromImageParams``)
            and ``timeout``.
    """

    # Daytona's interpreter reports only `Exception` subclasses in its structured
    # error output, so the final-answer control-flow exception generated by the
    # base class must not derive from `BaseException`.
    FINAL_ANSWER_EXCEPTION_BASE = "Exception"

    def __init__(
        self,
        additional_imports: list[str],
        logger: "AgentLogger",
        allow_pickle: bool = False,
        **kwargs: Any,
    ):
        super().__init__(additional_imports, logger, allow_pickle)
        self._daytona = Daytona()
        self.sandbox = self._daytona.create(**kwargs)
        try:
            self.context = self.sandbox.code_interpreter.create_context()
            self.installed_packages = self.install_packages(additional_imports)
        except BaseException:
            # The sandbox is a remote resource created by this constructor: if the
            # rest of the initialization fails, the caller never receives the
            # instance and could not release it, so release it here.
            self.cleanup()
            raise
        self.logger.log("Daytona sandbox is running", level=LogLevel.INFO)

    def install_packages(self, additional_imports: list[str]) -> list[str]:
        """Install packages and make sure the live interpreter can import them.

        Daytona sandboxes run Python with a non-writable system site-packages, so
        ``pip install`` silently falls back to a user-site install while still
        exiting 0. The interpreter context is a long-running process started before
        that user-site directory existed, so the directory is missing from its
        ``sys.path`` and the installed packages are not importable.

        pip itself already does the right thing in every environment (virtualenv,
        writable, and non-writable system Python alike); the only gap is user-site
        visibility in the running process, which this override repairs after the
        install. The user-site directory is inserted before system site-packages,
        mirroring interpreter-startup ordering (``site.py`` does the same), so
        versions installed for the agent shadow copies preinstalled in the image.

        Proposed upstream as the base-class default behavior
        (huggingface/smolagents#2724); this override disappears once that lands.

        Args:
            additional_imports: Package names to install.

        Returns:
            The list of installed packages.

        Raises:
            AgentError: If the installation command fails in the sandbox.
        """
        if additional_imports:
            code = dedent(
                f"""
                import importlib
                import os
                import site
                import subprocess
                import sys

                subprocess.run(
                    [sys.executable, "-m", "pip", "install", *{additional_imports!r}],
                    check=True,
                )

                user_site = site.getusersitepackages()
                if os.path.isdir(user_site) and user_site not in sys.path:
                    # Insert before system site-packages, mirroring site.py startup
                    # ordering, so agent-requested versions shadow preinstalled ones.
                    system_sites = set(getattr(site, "getsitepackages", lambda: [])())
                    indices = [index for index, path in enumerate(sys.path) if path in system_sites]
                    sys.path.insert(min(indices) if indices else len(sys.path), user_site)
                importlib.invalidate_caches()
                """
            )
            code_output = self.run_code_raise_errors(code)
            self.logger.log(code_output.logs)
        return additional_imports

    def run_code_raise_errors(self, code: str) -> CodeOutput:
        """Execute Python code in the sandbox and return the result.

        Args:
            code: Python code to execute.

        Returns:
            Code output containing the result, logs, and whether it is the final answer.

        Raises:
            AgentError: If the executed code raised an error in the sandbox.
        """
        result = self.sandbox.code_interpreter.run_code(code, context=self.context)

        logs = result.stdout
        if result.stderr:
            logs = f"{logs}\n{result.stderr}".strip()

        if result.error:
            if result.error.name == self.FINAL_ANSWER_EXCEPTION:
                final_answer = self.deserialize_final_answer(result.error.value, self.allow_pickle)
                return CodeOutput(output=final_answer, logs=logs, is_final_answer=True)

            error_message = (
                f"{logs}\n"
                f"Executing code yielded an error:\n"
                f"{result.error.name}\n"
                f"{result.error.value}\n"
                f"{result.error.traceback}"
            )
            raise AgentError(error_message, self.logger)

        return CodeOutput(output=result.stdout.strip() or None, logs=logs, is_final_answer=False)

    def cleanup(self) -> None:
        """Release the Daytona sandbox.

        Idempotent and safe to call at any point, including after a partially
        failed initialization, per the smolagents executor contract.
        """
        try:
            if hasattr(self, "sandbox"):
                self.logger.log("Shutting down Daytona sandbox...", level=LogLevel.INFO)
                self.sandbox.delete()
                del self.sandbox
                self.logger.log("Daytona sandbox cleanup completed", level=LogLevel.INFO)
        except Exception as e:
            self.logger.log_error(f"Error during Daytona cleanup: {e}")
